# OBTER ENDPOINTS
BRONZE = 'bronze'
SILVER = 'silver'
GOLD = 'gold'
PEOPLE_TABLE = "people"
PLANETS_TABLE = "planets"
SPECIES_TABLE = "species"
STARSHIPS_TABLE = "starships"
VEHICLES_TABLE = "vehicles"
FILMS_TABLE = "films"
VAULT_SECRET_URI = '/v1/app/data/robo/hml/extrato/extrato-letters'